# Generated by Django 5.1.6 on 2025-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='g_att',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='g_reg',
            field=models.BooleanField(default=False),
        ),
    ]
